### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by nk932714** [renganatha10/whatspp-PWA#3]
Please add readme to how to use this script

**Comment by renganatha10** [comment]
HI You can follow this
```
      git clone https://github.com/renganatha10/whatspp-PWA.git
      cd whatspp-PWA
      npm install
      npm run dev
```

**Comment by nk932714** [comment]
Thanks Renganatha. 
Are you working currently on this project because i really like this script and wants to login using qr code.
This would be best alternative of web whatsapp online version.

**Comment by renganatha10** [comment]
@nk932714 I am not currently working on this. I created this repo to understand PWA. you can fork and use it

**Comment by nk932714** [comment]
Thanks
